import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import Header from './header';
import Footer from './footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode,
  params: { locale: string}
}) {
  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <Header locale={params.locale} />
        <main>{children}</main>
        <Footer/>
        </body>
    </html>
  )
}
